name: Terraform validate

on:
  push:
    branches:
      - master
    paths:
      - "**"
      - ".github/workflows/terraform.yaml"
env:
  TF_VAR_cluster_name: "foo"
  TF_VAR_token: "token"
  TF_VAR_rancher_url: "https://example.com"
  TF_VAR_prj_name: "awesome prj"
  TF_VAR_namespaces: '["ns1", "ns2"]'
  TF_VAR_elastic_endpoint: "example.com"
  TF_VAR_elastic_password: "foobar"
jobs:
  validate:
    name: "Run terraform validate"
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: echo -n "::set-output name=stdout::$(terraform validate -no-color)"

